id = "shadowtree"
name = "Shadowtree"
description = "Shadowtree TOML config support."
version = "0.1.0"
schema_version = 1
authors = ["yusing"]
repository = "https://github.com/yusing/shadowtree"

[grammars.toml]
repository = "https://github.com/tree-sitter/tree-sitter-toml"
commit = "342d9be207c2dba869b9967124c679b5e6fd0ebe"

[language_servers.shadowtree-lsp]
name = "Shadowtree LSP"
languages = ["Shadowtree TOML"]

[language_servers.shadowtree-lsp.language_ids]
"Shadowtree TOML" = "toml"
